services:
  - type: web
    name: ocr-llm-server
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        value: <AIzaSyBgG0Js0PwIYTRae2-mkPpV1MnDwG_ubE8>